---
id: HashTable
name: HashTable
full: Hash table client library
description: Provides an abstract API to access various hash table implementations.
list: dev
type: library
authors:
  -
    name: Michael Slusarz
    user: slusarz
    email: slusarz@horde.org
    active: true
    role: lead
version:
  release: 1.2.7
  api: 1.2.0
state:
  release: stable
  api: stable
license:
  identifier: LGPL-2.1
  uri: http://www.horde.org/licenses/lgpl21
dependencies:
  required:
    php: ^5.3 || ^7
    pear:
      pear.horde.org/Horde_Exception: ^2
  optional:
    pear:
      pear.horde.org/Horde_Log: ^2
      pear.horde.org/Horde_Memcache: ^2
      pear.horde.org/Horde_Vfs: ^2
      pear.nrk.io/Predis: ^1
