---
id: HashTable
name: HashTable
full: Hash table client library
description: A library that provides access to various hash table implementations.
list: dev
type: library
authors:
  -
    name: Michael Slusarz
    user: slusarz
    email: slusarz@horde.org
    active: false
    role: lead
version:
  release: 2.0.0alpha4
  api: 2.0.0alpha1
state:
  release: alpha
  api: alpha
license:
  identifier: LGPL-2.1-only
  uri: http://www.horde.org/licenses/lgpl21
dependencies:
  required:
    php: ^7.4 || ^8
    composer:
      horde/exception: ^3
  optional:
    composer:
      horde/log: ^3
      horde/memcache: ^3
      horde/vfs: ^3
      predis/predis: ^1.1
