<?php

declare(strict_types=1);

/**
 * Copyright 2026 Horde LLC (http://www.horde.org/)
 *
 * See the enclosed file LICENSE for license information (LGPL). If you
 * did not receive this file, see http://www.horde.org/licenses/lgpl21.
 *
 * @package HashTable
 */

namespace Horde\HashTable\Redis\Config;

/**
 * Maps legacy Horde conf.php arrays into typed RedisConfig objects.
 *
 * The array format is generated by horde/base conf.xml and looks like:
 *
 *   $conf['hashtable']['params'] = [
 *       'hostspec'         => ['host1', 'host2'],
 *       'port'             => ['6379', '6379'],
 *       'protocol'         => 'tcp',
 *       'replication'      => 'sentinel',  // or 'none'
 *       'service'          => 'mymaster',
 *       'password'         => 'secret',
 *       'username'         => 'horde',
 *       'sentinelPassword' => 'sentinel_secret',
 *       'database'         => 0,
 *       'persistent'       => true,
 *       'socket'           => '/var/run/redis.sock',
 *   ];
 */
final class RedisConfigMapper
{
    /**
     * @param array  $params  The hashtable.params array from conf.php.
     * @param string $prefix  Key prefix (from hashtable.prefix config).
     */
    public static function fromArray(array $params, string $prefix = 'hht_'): RedisConfig
    {
        $protocol = (string) ($params['protocol'] ?? 'tcp');
        $replication = (string) ($params['replication'] ?? 'none');
        $password = self::nullIfEmpty($params['password'] ?? null);
        $username = self::nullIfEmpty($params['username'] ?? null);
        $database = (int) ($params['database'] ?? 0);
        $persistent = !empty($params['persistent']);

        if ($replication === 'sentinel') {
            return new SentinelConfig(
                sentinels: self::buildNodeList($params),
                service: (string) ($params['service'] ?? 'mymaster'),
                password: $password,
                username: $username,
                sentinelPassword: self::nullIfEmpty($params['sentinelPassword'] ?? null),
                prefix: $prefix,
                database: $database,
                persistent: $persistent,
            );
        }

        if ($protocol === 'unix') {
            return new SingleNodeConfig(
                node: new RedisNode('127.0.0.1'),
                password: $password,
                username: $username,
                prefix: $prefix,
                database: $database,
                persistent: $persistent,
                socket: $params['socket'] ?? null,
            );
        }

        $hostspec = $params['hostspec'] ?? ['127.0.0.1'];
        $host = is_array($hostspec) ? (string) ($hostspec[0] ?? '127.0.0.1') : (string) $hostspec;
        $port = $params['port'] ?? [6379];
        $portInt = is_array($port) ? (int) ($port[0] ?? 6379) : (int) $port;

        return new SingleNodeConfig(
            node: new RedisNode(host: trim($host), port: $portInt),
            password: $password,
            username: $username,
            prefix: $prefix,
            database: $database,
            persistent: $persistent,
        );
    }

    /**
     * Builds a list of RedisNode from parallel hostspec/port arrays.
     *
     * @return list<RedisNode>
     */
    private static function buildNodeList(array $params): array
    {
        $hosts = (array) ($params['hostspec'] ?? []);
        $ports = (array) ($params['port'] ?? []);
        $nodes = [];

        foreach ($hosts as $i => $host) {
            $port = (int) trim((string) ($ports[$i] ?? '26379'));
            $nodes[] = new RedisNode(host: trim((string) $host), port: $port);
        }

        return $nodes;
    }

    private static function nullIfEmpty(mixed $value): ?string
    {
        if ($value === null || $value === '') {
            return null;
        }

        return (string) $value;
    }
}
